### PR TITLE
Add rails_best_practices to AbleCop (and bump up to version 0.3.0)

### PR DESCRIPTION
**Pull request by dennmart**
This branch sets up the [rails_best_practices](https://github.com/railsbp/rails_best_practices) gem and its [Pronto runner](https://github.com/mmozuras/pronto-rails_best_practices). I also bumped up the version to 0.3.0 because of a few internal changes (and because bumping up gem versions is fun!).

Due to the rails_best_practices gem looking for its configuration file in the `config/` directory of a project, as well as the configuration file not being a dot-file like the other configuration files we copy over, I had to modify the way the Rails generator copies the file. The way it will work now is by setting up a hash constant that will contain the filename we want to copy from the gem as the key, and the destination as its value.

I also added a [CHANGELOG](https://github.com/ableco/gems.able.co/blob/5c4128a63f84b06552a5d89c8de33b13d85fb1d4/ablecop/CHANGELOG.md) in order to keep track of the changes made to the gem in different versions. I also merged a few changes from the master branch.

---
### Call for help from other developers!

I'm using the default configuration for the rails_best_practices gem. I did a quick run with this configuration on both the C- and P- repos, and both repos had multiple warnings (C- had 24, P- had 74). Most of them seemed to be smaller fixes: For example, almost half of the warnings on the Core repo were for [adding database indices](http://rails-bestpractices.com/posts/2010/07/24/always-add-db-index/). But I didn't check deeper into which of these warnings are something we shouldn't be too strict about.

Before merging this, I wanted to ask for input from other devs about which of the defaults we should change for this gem. The default configuration is [here](https://github.com/railsbp/rails_best_practices#custom-configuration) and detailed explanations for each can be found [here](http://rails-bestpractices.com/).

### CODE REVIEW

**Comment by dennmart** [comment]
I ran the code analysis from this branch on the C- and P- repos, and these are the warnings we got from `rails_best_practices`:

### C- (24 warnings)
- [Always add DB Index](http://rails-bestpractices.com/posts/2010/07/24/always-add-db-index/) (x11)
- [Law of Demeter](http://rails-bestpractices.com/posts/2010/07/24/the-law-of-demeter/) (x2)
- Remove unused methods (x7)
- [Restrict auto-generated routes](http://rails-bestpractices.com/posts/2011/08/19/restrict-auto-generated-routes/) (x1)
- [Use query attribute](http://rails-bestpractices.com/posts/2010/10/03/use-query-attribute/) (x2)
- [Use scope access](http://rails-bestpractices.com/posts/2010/07/20/use-scope-access/) (x1)

---

### P- (75 warnings)
- [Always add DB Index](http://rails-bestpractices.com/posts/2010/07/24/always-add-db-index/) (x5)
- [Law of Demeter](http://rails-bestpractices.com/posts/2010/07/24/the-law-of-demeter/) (x26)
- [Move code into model](http://rails-bestpractices.com/posts/2010/07/24/move-code-into-model/) (x1)
- [Move model logic into the model](http://rails-bestpractices.com/posts/2010/07/21/move-model-logic-into-the-model/) (x9)
- [Overuse route customizations](http://rails-bestpractices.com/posts/2010/07/22/overuse-route-customizations/) (x1)
- Remove unused methods (x20)
- [Restrict auto-generated routes](http://rails-bestpractices.com/posts/2011/08/19/restrict-auto-generated-routes/) (x4)
- [Simplify render in controllers](http://rails-bestpractices.com/posts/2010/12/12/simplify-render-in-controllers/) (x1)
- [Use query attribute](http://rails-bestpractices.com/posts/2010/10/03/use-query-attribute/) (x4)
- [Use say and say_with_time in migrations to make a useful migration log](http://rails-bestpractices.com/posts/2010/08/19/use-say-and-say_with_time-in-migrations-to-make-a-useful-migration-log/) (x1)
- [Remove trailing whitespace](http://rails-bestpractices.com/posts/2010/12/02/remove-trailing-whitespace/)

**Comment by dennmart** [comment]
I did some spot checking with some of these errors, and they make sense to update on our code.

The only check that's a bit spotty is the "remove unused methods" check. There were a couple of false positives in the checks I did (methods flagged by the gem as being unused, but are actually being used somewhere in our code). This seems to be a limitation of the gem (https://github.com/railsbp/rails_best_practices/issues/102).

There is a whitelist to be able to skip checking some of these methods, which is a useful workaround. For C-, there was only 1-2 methods that need to be added to this whitelist, but I'm not sure for P-. The check seems useful but I don't want it raising too many false alarms.

Any thoughts?

**Comment by dennmart** [comment]
I didn't get any comments on my call for help, so I'm going to proceed with merging this. If any issues come up with this, we'll address them separately.

FYI: I've been tagging each release so if you don't want to use this version of the gem yet, just make sure to use the `tag` option in the Gemfile. The README has been updated with this information.

**Comment by juliogarciag** [comment]
@dennmart Sorry for not give feedback before. I took a light look at the gem then. I find `rails_best_practices` useful but with a problem with his capacity to be overridable. It's not possible to override it the same way other linters could, because there's no way to use the yaml merge features to disable a review. Do you know if there's other way to make customizations to it?

**Comment by dennmart** [comment]
@juliogarciag It seems like currently there's no way to remove a configuration check from those files. I'm going to open a separate issue to explore other ways to do this.

**Pull request merged**
